
name = "Pixel Art Color Picker"
brief = "Helper program for the math of pixel art coloring"
desc = """
This is a tool I made to help make palettes for pixel art. It uses
the formulas provided by a prominent pixel art tutorial series,
[PixelBlog](https://www.slynyrd.com/blog/2018/1/10/pixelblog-1-color-palettes).
All the parameters are configurable, including editable quadratic
bezier curves. It allows saving and loading palette configuration as
a JSON file, and can export them to .pal files that most image editing software can
understand.

The tool was made using Processing, without using external GUI libraries.
"""

[left_bar]
Language = "Processing"
"Github Repo" = {url="https://github.com/Phlosioneer/ColorPicker", text="Phlosioneer/ColorPicker"}
