
name = "Connect Four"
brief = "Same game, in several languages"
desc = """
**Connect Four** was a multi-language project. I implemented the game
Connect Four using standard text I/O in several languages. Similar to the
Rosetta Code project, the goal was to make the same thing in many languages to
see the differences between how the languages operate, and how large or small
each codebase was.
"""

[left_bar]
Languages = "C"
"C Repo" = { url="https://github.com/Phlosioneer/ConnectFourC", text="Phlosioneer/ConnectFourC" }

[[screenshots]]
image = "ConnectFourC.png"
desc = """
This is from the C implementation of Connect Four, for Windows. It uses the
windows console API to switch the command prompt from OEM to Utf-8, checks that
the user's console font supports Utf-8, and then uses the Box Drawing characters
to draw the grid.
"""
